# Generated by Django 3.1 on 2020-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
