# Generated by Django 3.1 on 2020-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200817_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
